version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysqlDB
    networks:
      - my-net
    environment:
      MYSQL_DATABASE: 'newDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'  
    ports:
      - '3308:3306'

networks:
    my-net:
        external: true

